export const styles = {
  page: { fontFamily: "'Inter', sans-serif", color: "#1C2430", minHeight: "100vh", padding: "40px 24px 80px", maxWidth: 720, margin: "0 auto" },
  header: { marginBottom: 24 },
  eyebrow: { fontFamily: "'JetBrains Mono', monospace", fontSize: 12, letterSpacing: "0.12em", textTransform: "uppercase", color: "#8B9A5B", marginBottom: 8 },
  title: { fontFamily: "'Fraunces', serif", fontWeight: 500, fontSize: "clamp(24px, 4vw, 30px)", margin: 0, lineHeight: 1.2 },
  sectionHeading: { fontFamily: "'Fraunces', serif", fontSize: 16, fontWeight: 500, marginBottom: 12 },

  card: { background: "#FFFFFF", border: "1px solid #E7E2D6", borderRadius: 14, padding: "18px 20px" },

  coverageTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12, gap: 12, flexWrap: "wrap" },
  coveragePct: { fontFamily: "'JetBrains Mono', monospace", fontSize: 28, fontWeight: 500, lineHeight: 1 },
  coverageLabel: { fontSize: 12, color: "#6B7280", marginTop: 3 },
  addBtn: { background: "#1C2430", color: "#F6F4EF", border: "none", borderRadius: 999, padding: "9px 15px", fontSize: 12.5, fontWeight: 500, cursor: "pointer", whiteSpace: "nowrap" },
  coverageBar: { display: "flex", width: "100%", height: 9, borderRadius: 5, overflow: "hidden" },

  pendingList: { display: "flex", flexDirection: "column", gap: 8 },
  pendingCard: { display: "flex", alignItems: "center", gap: 10, background: "#FFFFFF", border: "1px dashed #C08A2E77", borderRadius: 12, padding: "13px 15px", cursor: "pointer", textAlign: "left", font: "inherit", width: "100%" },
  pendingMerchant: { fontSize: 14, fontWeight: 500 },
  pendingMeta: { fontSize: 11.5, color: "#8B95A5", marginTop: 2 },
  pendingAmount: { fontFamily: "'JetBrains Mono', monospace", fontSize: 14, color: "#C08A2E" },
  tierGlyph: { width: 16, textAlign: "center", fontSize: 13, flexShrink: 0 },

  spectrumLabelRow: { display: "flex", justifyContent: "space-between", fontFamily: "'JetBrains Mono', monospace", fontSize: 10.5, letterSpacing: "0.08em", textTransform: "uppercase", color: "#8B95A5", marginBottom: 8 },
  spectrumBar: { display: "flex", width: "100%", height: 11, borderRadius: 6, overflow: "hidden" },

  sliceRow: { display: "flex", alignItems: "center", gap: 20, flexWrap: "wrap" },
  sliceChartWrap: { position: "relative", width: 168, height: 168, flexShrink: 0 },
  sliceCenter: { position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", pointerEvents: "none" },
  sliceCenterAmt: { fontFamily: "'JetBrains Mono', monospace", fontSize: 15, fontWeight: 500 },
  sliceCenterLabel: { fontSize: 10.5, color: "#8B95A5", marginTop: 2, textAlign: "center", maxWidth: 90 },
  sliceLegend: { flex: 1, minWidth: 160, display: "flex", flexDirection: "column", gap: 8 },
  sliceLegendRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13 },
  sliceLegendLabel: { flex: 1, color: "#3B4453" },
  sliceLegendPct: { fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: "#6B7280" },
  dot: { width: 8, height: 8, borderRadius: "50%", display: "inline-block", flexShrink: 0 },

  projGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10 },
  projCard: { background: "#1C2430", color: "#F6F4EF", borderRadius: 12, padding: "14px 10px", textAlign: "center" },
  projLabel: { fontSize: 10.5, letterSpacing: "0.06em", textTransform: "uppercase", color: "#A8B0BE", marginBottom: 6 },
  projValue: { fontFamily: "'JetBrains Mono', monospace", fontSize: 16, fontWeight: 500, color: "#C08A2E" },
  cutToggleRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", marginBottom: 12 },
  cutToggleLabel: { fontSize: 12, color: "#6B7280" },
  cutToggleGroup: { display: "flex", gap: 6 },

  ruleItem: { fontSize: 13, color: "#5C8168", fontStyle: "italic", padding: "8px 0", borderBottom: "1px solid #E7E2D6" },

  connectRow: { display: "flex", alignItems: "center", gap: 12, padding: "12px 0", borderBottom: "1px solid #E7E2D6" },
  connectMain: { flex: 1, minWidth: 0 },
  connectName: { fontSize: 14, fontWeight: 500 },
  connectSub: { fontSize: 12, color: "#8B95A5", marginTop: 2 },
  connectStatusOk: { fontSize: 12, color: "#3F6E5B", fontWeight: 500, whiteSpace: "nowrap" },
  connectStatusManual: { fontSize: 12, color: "#C08A2E", fontWeight: 500, whiteSpace: "nowrap" },

  list: { display: "flex", flexDirection: "column", gap: 2 },
  row: { display: "flex", alignItems: "center", gap: 10, padding: "12px 4px", borderBottom: "1px solid #E7E2D6" },
  rowMain: { flex: 1, minWidth: 0 },
  rowMerchant: { fontSize: 14, fontWeight: 500 },
  rowMeta: { fontSize: 11.5, color: "#8B95A5", marginTop: 2 },
  rowAmount: { fontFamily: "'JetBrains Mono', monospace", fontSize: 13.5, width: 68, textAlign: "right" },
  rankChip: { fontSize: 11, fontWeight: 500, border: "1px solid", borderRadius: 999, padding: "5px 9px", whiteSpace: "nowrap", cursor: "pointer" },

  overlay: { position: "fixed", inset: 0, background: "rgba(28,36,48,0.5)", display: "flex", alignItems: "flex-end", justifyContent: "center", zIndex: 50 },
  modal: { background: "#F6F4EF", width: "100%", maxWidth: 480, borderRadius: "18px 18px 0 0", padding: "20px 20px 24px" },
  modalHeader: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 14 },
  modalMerchant: { fontFamily: "'Fraunces', serif", fontSize: 18, fontWeight: 500 },
  modalAmount: { fontFamily: "'JetBrains Mono', monospace", fontSize: 15, color: "#6B7280" },
  modalTitle: { fontFamily: "'Fraunces', serif", fontSize: 18, fontWeight: 500, marginBottom: 6 },
  modalSub: { fontSize: 13, color: "#6B7280", marginBottom: 16, lineHeight: 1.5 },
  formInput: { width: "100%", border: "1px solid #E7E2D6", borderRadius: 10, padding: "12px 14px", fontSize: 14, fontFamily: "inherit", background: "#FFFFFF", marginBottom: 10 },
  chatLog: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 14, maxHeight: 220, overflowY: "auto" },
  bubbleApp: { alignSelf: "flex-start", background: "#FFFFFF", border: "1px solid #E7E2D6", borderRadius: "12px 12px 12px 4px", padding: "10px 14px", fontSize: 14, maxWidth: "85%" },
  bubbleUser: { alignSelf: "flex-end", background: "#1C2430", color: "#F6F4EF", borderRadius: "12px 12px 4px 12px", padding: "10px 14px", fontSize: 14, maxWidth: "85%" },
  errorText: { color: "#A83B32", fontSize: 13 },
  chatInputRow: { display: "flex", gap: 8, marginBottom: 10 },
  chatInput: { flex: 1, border: "1px solid #E7E2D6", borderRadius: 10, padding: "12px 14px", fontSize: 14, fontFamily: "inherit", background: "#FFFFFF" },
  chatSend: { background: "#3F6E5B", color: "#fff", border: "none", borderRadius: 10, padding: "0 18px", fontSize: 14, fontWeight: 500, cursor: "pointer" },
  modalActions: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 12 },
  modalBtnPrimary: { background: "#3F6E5B", color: "#fff", border: "none", borderRadius: 10, padding: "14px", fontSize: 14.5, fontWeight: 500, cursor: "pointer" },
  modalClose: { background: "none", border: "none", color: "#8B95A5", fontSize: 12.5, cursor: "pointer", display: "block", margin: "0 auto" },
};
